name = "aged-lake-1065" compatibility_date = "2025-08-21"
  "name": "cloudflare-deploy",
  "pages_build_output_dir": "public",
  "version": "0..0",
  "private": true,
  "scripts": {
    "deploy": "wrangler publish",
    "start": "wrangler dev"
    }

